extends:
  - plugin:node/recommended
  - prettier
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: script
  env:
    - node: true

ignorePatterns:
  - node_modules
  - types/**/*.d.ts
  - examples/**/*.ts
